-- program_registry: 10 TC programs, hand-seeded due to typo'd prog_name_en variants.
-- One program_id per logical program; aliases array maps every variant in source.
-- estimates_match_keywords / budget_keywords / throne_themes power the lineage joins.

CREATE OR REPLACE TABLE `agency2026ot-tr8-0429.gc_policy.program_registry` (
  program_id STRING NOT NULL,
  display_name STRING NOT NULL,
  display_name_fr STRING,
  short_name STRING,
  aliases ARRAY<STRING>,
  estimates_match_keywords ARRAY<STRING>,
  budget_keywords ARRAY<STRING>,
  throne_themes ARRAY<STRING>,
  notes STRING
);

INSERT INTO `agency2026ot-tr8-0429.gc_policy.program_registry`
  (program_id, display_name, display_name_fr, short_name, aliases,
   estimates_match_keywords, budget_keywords, throne_themes, notes)
VALUES
  ('izev',
   'Incentives for Zero-Emission Vehicles Program',
   'Incitatifs pour les véhicules zéro émission',
   'iZEV',
   ['Incentives for Zero-emission vehicles program',
    'Incentives for Zero-Emission Vehicles Program (iZEV)',
    'Incentives for Zero-emission vehicles program (IZEV)'],
   ['zero-emission vehicle', 'iZEV', 'incentives for zero-emission'],
   ['iZEV', 'zero-emission vehicle', 'electric vehicle', 'EV rebate', 'ZEV'],
   ['climate', 'net-zero', 'clean transition', 'electric vehicle', 'green economy'],
   'Canary program — Tesla 2024 ≈ $232.5M'),

  ('ntcf',
   'National Trade Corridors Fund',
   'Fonds national des corridors commerciaux',
   'NTCF',
   ['National Trade Corridors Fund'],
   ['National Trade Corridors', 'trade corridor'],
   ['trade corridor', 'NTCF', 'supply chain', 'port infrastructure'],
   ['supply chain', 'trade', 'infrastructure'],
   NULL),

  ('ferry',
   'Ferry Services Contribution Program',
   'Programme de contribution aux services de traversier',
   'Ferry',
   ['Ferry Services Contribution Program'],
   ['Ferry Services', 'ferry contribution'],
   ['ferry service', 'inter-provincial ferry'],
   ['regional connectivity', 'transportation'],
   NULL),

  ('rstpp',
   'Enhanced Road Safety Transfer Payment Program',
   'Programme de paiements de transfert pour la sécurité routière',
   'RSTPP',
   ['Road Safety  Transfer Payment Program / Enhanced Road Safety Transfer Payment Program',
    'Enhanced Road Safety Transfer Payment Program',
    'Road Safety Transfer Payment Program'],
   ['Road Safety', 'road safety transfer'],
   ['road safety', 'enhanced road safety'],
   ['safety', 'roads'],
   NULL),

  ('acip',
   'Airport Critical Infrastructure Program',
   'Programme des infrastructures essentielles des aéroports',
   'ACIP',
   ["Contributions to Support the Recovery of Canada's Airport System  / Airport Critical Infrastructure Program",
    'Airport Critical Infrastructure Program'],
   ['Airport Critical Infrastructure', 'airport recovery'],
   ['airport', 'aviation recovery', 'COVID-19 airport'],
   ['recovery', 'aviation', 'pandemic recovery'],
   NULL),

  ('rprp',
   'Remote Passenger Rail Program',
   'Programme des services ferroviaires voyageurs en régions éloignées',
   'RPRP',
   ['Remote Passenger Rail Program'],
   ['Remote Passenger Rail'],
   ['remote rail', 'passenger rail', 'remote community rail'],
   ['regional connectivity', 'remote communities'],
   NULL),

  ('acap',
   'Airports Capital Assistance Program',
   "Programme d'aide aux immobilisations aéroportuaires",
   'ACAP',
   ['Airports Capital Assistance Program'],
   ['Airports Capital Assistance'],
   ['airport capital', 'small airport'],
   ['regional aviation', 'infrastructure'],
   NULL),

  ('rsip',
   'Rail Safety Improvement Program',
   "Programme d'amélioration de la sécurité ferroviaire",
   'RSIP',
   ['Rail Safety Improvement Program  / Rail Safety Improvement Program: Infrastructure  Technology and Research Component',
    'Rail Safety and Improvement Program  / Rail Safety Improvement Program: Infrastructure  Technology and Research Component',
    'Rail Safety Improvement Program: Infrastructure  Technology and Research Component'],
   ['Rail Safety Improvement', 'rail safety'],
   ['rail safety', 'grade crossing', 'railway safety'],
   ['safety', 'rail'],
   NULL),

  ('ppccw',
   "Program to Protect Canada's Coastlines and Waterways",
   'Programme de protection des côtes et des voies navigables du Canada',
   'PPCCW',
   ["Program to Protect Canada's Coastlines and Waterways (PPCCW) / High Arctic Community Harbour Infrastructure Contribution Program"],
   ['Coastlines and Waterways', 'High Arctic'],
   ['oceans protection plan', 'coastline', 'waterways'],
   ['oceans', 'coastal', 'environment'],
   NULL),

  ('cpfp',
   'Community Participation Funding Program',
   'Programme de financement de la participation communautaire',
   'CPFP',
   ['Community Participation Funding Program'],
   ['Community Participation', 'community engagement'],
   ['community participation', 'public engagement'],
   ['engagement', 'community'],
   NULL);
